### ISSUE TITLE
Python3 support for jupyter notebook?

### ISSUE THREAD

**Issue by zak-hassan** [rustyrazorblade/ipython-cql#1]
Hi,

I was doing some experimentation with your module and tried to do the following 
`%load_ext cql`

Any thoughts on any workarounds?

```bash
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cql/__init__.py", line 67
    print "Using keyspace %s" % line
                            ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by rustyrazorblade** [comment]
Python 3 replaced print with a print function.  I think you can replace that line with:

`print("Using keyspace {}".format(line))` 

I'm not really maintaining this project, it was a one off I mostly wrote at an airport :)

**Comment by zak-hassan** [comment]
@rustyrazorblade No worries. I saw the project and thought it would be cool to test out. Thanks
